#!/usr/bin/env bash
#
# mksite - Create a stupid simple website.

templ='<!DOCTYPE html><html lang=en><head><link href="data:image/png;base64," rel=icon type="image/png"><title>dylan</title><meta name=viewport content="width=device-width"><style>body{overflow-y:scroll}img,main{display:block;margin:25px auto}main{padding:20px;max-width:600px;font-family:sans-serif;line-height:1.5}img{max-width:100%}</style></head><body><main>{{content}}</main></body></html>'

mkdir -p .site/images

for md in src/index.md src/pages/*.md; do
    file_name=${md##*/}

    [[ $file_name != index.md ]] &&
        home="<a href='/'>home</a>"


    minify --type html \
        <<< "${templ/'{{content}}'/${home}$(mdtohtml "$md")}" \
        > ".site/${file_name/%.md/.html}"

    home=
done

cd .site/images || exit

for img in ~/Pictures/site/*.jpg; do (
    file_name=${img##*/}
    x2=${file_name/%.jpg/-2x.jpg}

    convert "$img" -resize 600x\>  "$file_name"
    convert "$img" -resize 1200x\> "$x2"

    jpegoptim -s "$file_name" "$x2"

    img2webp -lossy -q 90 "$file_name" -o "${file_name%.jpg}.webp"
    img2webp -lossy -q 90 "$x2" -o "${x2%.jpg}.webp"
) & done

wait
