#!/usr/bin/env bash
#
# mksite - Create a stupid simple website.

templ='<!DOCTYPE html><html lang=en><head><meta name="description" content="I like to dream"/><link href="data:image/png;base64," rel=icon type="image/png"><title>blckk</title><meta name=viewport content="width=device-width"><style>body{overflow-y:scroll;font-family:sans-serif;color:#000;background-color:#fff;margin:0}img,main,pre>code{display:block;margin:0 auto}main{max-width:600px;line-height:1.6;word-wrap:break-word}img{max-width:100%}pre>code{padding:20px;white-space:pre-wrap}code{background:#eee;padding:2px}blockquote{border-left:7px solid #ddd;padding:0 14px;color:#666;margin:0}h1,h2,h3,h4{line-height:1.2}hr{border: 2px solid #ddd}input{position:absolute;z-index:99}input[type=checkbox]:checked ~ section{filter:invert(100%);background-color:#fff}section > :not(img){min-height:100vh}</style></head><body><input type=checkbox><section><main><br><br>{{content}}<br></main></section></body></html>'

[[ -z $1 ]] && rm -rf .site

mkdir -p .site/images

for md in src/*.md; do
    file_name=${md##*/}

    [[ $file_name != index.md ]] &&
        home="<a href='/'>blckk</a>"


    minify --type html \
        <<< "${templ/'{{content}}'/${home}$(pandoc "$md")}" \
        > ".site/${file_name/%.md/.html}"

    home=
done

[[ $1 ]] && exit
cd .site/images || exit

png_flags=(--speed 1 --skip-if-larger --strip -f --verbose --output)

for img in ~/Pictures/site/*.{jpg,png}; do (
    file_name=${img##*/}
    suffix=${file_name/*.}
    x2=${file_name/%.${suffix}/-2x.${suffix}}

    convert "$img" -resize 600x\>  "$file_name"
    convert "$img" -resize 1200x\> "$x2"

    case $suffix in
        jpg) jpegoptim -s "$file_name" "$x2" ;;
        png)
            pngquant "$file_name" "${png_flags[@]}" "$file_name"
            pngquant "$x2" "${png_flags[@]}" "$x2"
        ;;
    esac

    img2webp -lossy -q 90 "$file_name" -o "${file_name%.${suffix}}.webp"
    img2webp -lossy -q 90 "$x2" -o "${x2%.${suffix}}.webp"
) & done

wait
