#!/usr/bin/env bash
#
# mksite - Create a stupid simple website.

templ='<!DOCTYPE html><html lang=en><head><link href="data:image/png;base64," rel=icon type="image/png"><title>dylan</title><meta name=viewport content="width=device-width"><style>body{overflow-y:scroll}img,main{display:block;margin:25px auto}main{padding:0 20px;max-width:630px;font-family:sans-serif;line-height:1.5}img{max-width:100%}</style></head><body><main>{{content}}</main></body></html>'

for md in src/index.md src/pages/*.md; do
    file_name=${md##*/}
    minify --type html \
        <<< "${templ/'{{content}}'/$(mdtohtml "$md")}" \
        > "${file_name/%.md/.html}"
done

mkdir -p images
cd images || exit

for img in ~/Pictures/site/*.jpg; do (
    file_name=${img##*/}
    x2=${file_name/%.jpg/-2x.jpg}

    convert "$img" -resize 630x  "$file_name"
    convert "$img" -resize 1260x "$x2"

    jpegoptim -s "$file_name"
    jpegoptim -s "$x2"

    img2webp -lossy -q 75 "$file_name" -o "${file_name%.jpg}.webp"
    img2webp -lossy -q 75 "$x2" -o "${x2%.jpg}.webp"
) & done

wait
